#!/usr/bin/env bash
# Configure your Nginx server to have redirect_me redirecting to another page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello Word!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=DUv-r_OCoZo;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
