#!/usr/bin/env bash
# displays a list of currently running processes.
# show all processes, for all users, including users without TTY
# Display in a user-oriented format
# Show process hierarchy
ps -auxf
