#!/usr/bin/env bash
#configures the container so that Nginx is running as the nginx user.
sudo service nginx stop
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/nginx.conf
sudo pkill -9 apache
sudo service nginx start