#!/usr/bin/env bash
#configures Nginx to run as the nginx user in 7 lines or less
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill apache2
sudo -u nginx service nginx restart
