#!/usr/bin/env bash
#configures the container so that Nginx is running as the nginx user.
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache
su nginx -c "service nginx restart"